### ISSUE TITLE
Cannot reproduce performance gains with zfex.easyfec

### ISSUE THREAD

**Issue by NathanRichard** [WojciechMigda/zfex#157]
Hello,
First of all, thanks for publishing your work on zfex, I found it very interesting.
I tried reproducing your results locally ; I can using the bundled C benchmark, but I cannot using the python interface. On my tests, zfex.easyfec behaves very close to zfec.easyfec. For instance on 12 Mio data blocs :
```
zfex.easyfec.Encoder(2, 6) => 234.34 Mio/s
zfec.easyfec.Encoder(2, 6) => 222.86 Mio/s
```
Am I missing something or is this expected ? Maybe you optimized only the decoding ?

Best regards

**Comment by WojciechMigda** [comment]
Hello,
Thank you for your interest in `zfex`.
You are right, benchmarks provided were collected using bundled C program and are not yet available through python API. This requires additional work which is missing. As far as I remember, one of the hurdles involves requirement for aligned memory storage, which in python is non-trivial (if at all possible?) and I haven't figured out how to tackle this.
With best regards,

**Comment by NathanRichard** [comment]
Hello,
Thank you for your reply.
Ok it makes sense. I have no time right now to test updating the python binding but I will get back to you if that changes.
Thanks for your work on this project.
Best regards,
